[package]
name = "rust-dinf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
walkdir = "2.5.0"
file-size = "1.0.3"
thiserror = "1.0.59"